
version: '2'

volumes:
    database_data:
        driver: local

services:
    nginx:
        container_name: nginx-local
        image: daocloud.io/library/nginx:latest
        ports:
            - 80:80
        volumes:
            - ./docker/nginx/:/etc/nginx/conf.d/:ro
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        volumes_from:
            - php
    php:
        container_name: php-local
        build: ./docker/php/7.0
        expose:
            - 9000
        volumes:
            - /e/WechatCRM/:/var/www/WechatCRM/

    mysql:
        image: mysql:latest
        expose:
            - 3306
        volumes:
            - database_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: wangziqi
            MYSQL_DATABASE: it
            MYSQL_USER: root
            MYSQL_PASSWORD: wangziqi
